//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public string link { get; set; }
        public string image { get; set; }
        public decimal rate { get; set; }
        public decimal views { get; set; }
        public string description { get; set; }
        public int instructorId { get; set; }
        public Nullable<int> trackId { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Instructor Instructor { get; set; }
        public virtual Track Track { get; set; }
    }
}
