//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coursaty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public Track()
        {
            this.Courses = new HashSet<Cours>();
            this.Tracks1 = new HashSet<Track>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> parentTrack { get; set; }
        public bool ToDelete { get; set; }
    
        public virtual ICollection<Cours> Courses { get; set; }
        public virtual ICollection<Track> Tracks1 { get; set; }
        public virtual Track Track1 { get; set; }
    }
}
